### ISSUE TITLE
masaic tolerance

### ISSUE THREAD

**Issue by Yingxia-Liu** [hasanbdimran/Raster-Mosaic#1]
> tif_mosaic <- do.call(mosaic, tif_file_list)
Error in compareRaster(x, extent = FALSE, rowcol = FALSE, orig = TRUE,  : 
  different origin

I find the answer is to add the tolerance=0.5. 
But 
> tif_mosaic <- do.call(mosaic, tif_file_list,tolerance=0.5)
Error in do.call(mosaic, tif_file_list, tolerance = 0.5) : 
  unused argument (tolerance = 0.5)

Do you know how to deal with this problem?

**Comment by hasanbdimran** [comment]
My code here is written in python. The problem you are facing seems on R.

**Comment by Yingxia-Liu** [comment]
Sorry, my codes belong to R.
